services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bun-react-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATA_DIR=/app/data
      - SERVICE_NAME=Never Have I Ever API
      - CORS_ORIGINS=*
    volumes:
      # Mount for data persistence (books.json)
      - backend_data:/app/data
    healthcheck:
      test: ["CMD", "bun", "-e", "fetch('http://localhost:' + (process.env.PORT || 3001) + '/health').then(r=>r.json()).then(()=>process.exit(0)).catch(()=>process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bun-react-frontend
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - API_BASE_URL=${API_BASE_URL:-http://localhost:3001/api}
    restart: unless-stopped

volumes:
  backend_data:
    driver: local 